# MultiomePipe config yaml file

# Change those values to yours
User:
  input_dir: /home/dondia/run_MultiomePipe/input_neurips2021_BMMC
  output_dir: /home/dondia/run_MultiomePipe/output_neurips2021_BMMC
  
# Change any of those to True if you want to run it, else False
Run:
  # QC the GEX data
  QC_RNA: True
  # QC the ATAC data
  QC_ATAC: False

samples:
  site1_donor1:
  site1_donor2:
  site1_donor3:
  site2_donor1:
  site2_donor4:
  site2_donor5:
  site3_donor3:
  site3_donor6:
  site3_donor7:
  site3_donor10:
  site4_donor1:
  site4_donor8:
  site4_donor9:

IS_FILTERED: True
IS_ANNOTATED: True

QC_RNA:
  raw_data: True

  CellbenderRemoveBackgroundRNA:
    n_cells: 10
    cuda: '' # change to '--cuda' if CUDA is installed and working
    expected-cells:
       human_brain_3k: 300
       10X_granulocyte: 1000
    epochs: 50
    checkpoint_mins: 1
    projected_ambient_count_threshold: 0.05
    empty_drop_training_fraction: 0.05

  RawFilteringRNA:
    min_genes: 500
    min_cells: 5
    doublet_threshold: .15

  PlottingAnnotations:
    doublets: "Doublets" # Name all the clusters you want to remove like this
    celltypes: "cell_type"

### QC ATAC
QC_ATAC:
  ExportPseudobulk:
    variable: "VSN_cell_type"
    sample_id_col: "VSN_sample_id"
    n_cpu: 4
    normalize_bigwig: ""         # use "" if False, "--normalize_bigwig" if True
    split_pattern: "-"
    chromsizes: null 
# MACS2 peak calling parameters
  MACS2CallPeaks:
    format: "BEDPE"
    gsize: "hs"
    qvalue: 0.05
    shift: 73
    extsize: 146
    keep_dup: "all"
    call_summits: "--call-summits"
    nolambda: "--nolambda"
