# MultiomePipe config yaml file

# Change those values to yours
User:
  input_dir: /home/dondia/run_MultiomePipe/input_human_brain_3k
  output_dir: /home/dondia/run_MultiomePipe/output_human_brain_3k
  
# Change any of those to True if you want to run it, else False
Run:
  # QC the GEX data
  QC_RNA: True
  # QC the ATAC data
  QC_ATAC: False

samples:
  #10X_granulocyte: https://cf.10xgenomics.com/samples/cell-arc/1.0.0/pbmc_granulocyte_sorted_10k/pbmc_granulocyte_sorted_10k
  human_brain_3k: https://cf.10xgenomics.com/samples/cell-arc/1.0.0/human_brain_3k/human_brain_3k

IS_FILTERED: False
IS_ANNOTATED: False
IS_BATCHED: False

QC_RNA:
  raw_data: True

  CellbenderRemoveBackgroundRNA:
    n_splits: 10
    cuda: '' # change to '--cuda' if CUDA is installed and working
    expected-cells:
       human_brain_3k: 300
       10X_granulocyte: 1000
    epochs: 50
    checkpoint_mins: 1
    projected_ambient_count_threshold: 0.05
    empty_drop_training_fraction: 0.05

  RawFilteringRNA:
    min_genes: 500
    min_cells: 5
    doublet_threshold: .15

  PlottingAnnotations:
    doublets: "Doublets Undefined" # All the clusters you want to remove, e.g. "Doublets Undefined T.cells"
    celltype_key: "cell_type"

  ConcatanateAnnDataObjects:
    sample_key: ""
    batch_key: ""

### QC ATAC
QC_ATAC:
  ExportPseudobulk:
    variable: "VSN_cell_type"
    sample_id_col: "VSN_sample_id"
    n_cpu: 4
    normalize_bigwig: ""         # use "" if False, "--normalize_bigwig" if True
    split_pattern: "-"
    chromsizes: null 
# MACS2 peak calling parameters
  MACS2CallPeaks:
    format: "BEDPE"
    gsize: "hs"
    qvalue: 0.05
    shift: 73
    extsize: 146
    keep_dup: "all"
    call_summits: "--call-summits"
    nolambda: "--nolambda"