# MultiomePipe config yaml file

# Change those values to yours
User:
  input_dir: /home/dondia/run_MultiomePipe/input_neurips2021_BMMC
  output_dir: /home/dondia/run_MultiomePipe/output_neurips2021_BMMC
  
# Change any of those to True if you want to run it, else False
Run:
  # QC the GEX data
  QC_RNA: True
  # QC the ATAC data
  QC_ATAC: False

samples:
  site1_donor1:
    donor: "D1"
    weblink: "https://www.ncbi.nlm.nih.gov/geo/download/?acc=GSM6659419&format=file&file=GSM6659419%5FM1%5Fraw%5Ffeature%5Fbc%5Fmatrix%2Eh5"
  site1_donor2:
    donor: "D2"
    weblink: "https://www.ncbi.nlm.nih.gov/geo/download/?acc=GSM6659419&format=file&file=GSM6659419%5FM1%5Fraw%5Ffeature%5Fbc%5Fmatrix%2Eh5"
  site1_donor3:
    donor: "D3"
    weblink: "https://www.ncbi.nlm.nih.gov/geo/download/?acc=GSM6659419&format=file&file=GSM6659419%5FM1%5Fraw%5Ffeature%5Fbc%5Fmatrix%2Eh5"
  site2_donor1:
    donor: "D1"
    weblink: "https://www.ncbi.nlm.nih.gov/geo/download/?acc=GSM6659419&format=file&file=GSM6659419%5FM1%5Fraw%5Ffeature%5Fbc%5Fmatrix%2Eh5"
  site2_donor4:
    donor: "D4"
    weblink: "https://www.ncbi.nlm.nih.gov/geo/download/?acc=GSM6659419&format=file&file=GSM6659419%5FM1%5Fraw%5Ffeature%5Fbc%5Fmatrix%2Eh5"
  site2_donor5:
    donor: "D5"
    weblink: "https://www.ncbi.nlm.nih.gov/geo/download/?acc=GSM6659419&format=file&file=GSM6659419%5FM1%5Fraw%5Ffeature%5Fbc%5Fmatrix%2Eh5"
  site3_donor3:
    donor: "D3"
    weblink: "https://www.ncbi.nlm.nih.gov/geo/download/?acc=GSM6659419&format=file&file=GSM6659419%5FM1%5Fraw%5Ffeature%5Fbc%5Fmatrix%2Eh5"
  site3_donor6:
    donor: "D6"
    weblink: "https://www.ncbi.nlm.nih.gov/geo/download/?acc=GSM6659419&format=file&file=GSM6659419%5FM1%5Fraw%5Ffeature%5Fbc%5Fmatrix%2Eh5"
  site3_donor7:
    donor: "D7"
    weblink: "https://www.ncbi.nlm.nih.gov/geo/download/?acc=GSM6659419&format=file&file=GSM6659419%5FM1%5Fraw%5Ffeature%5Fbc%5Fmatrix%2Eh5"
  site3_donor10:
    donor: "D10"
    weblink: "https://www.ncbi.nlm.nih.gov/geo/download/?acc=GSM6659419&format=file&file=GSM6659419%5FM1%5Fraw%5Ffeature%5Fbc%5Fmatrix%2Eh5"
  site4_donor1:
    donor: "D1"
    weblink: "https://www.ncbi.nlm.nih.gov/geo/download/?acc=GSM6659419&format=file&file=GSM6659419%5FM1%5Fraw%5Ffeature%5Fbc%5Fmatrix%2Eh5"
  site4_donor8:
    donor: "D8"
    weblink: "https://www.ncbi.nlm.nih.gov/geo/download/?acc=GSM6659419&format=file&file=GSM6659419%5FM1%5Fraw%5Ffeature%5Fbc%5Fmatrix%2Eh5"
  site4_donor9:
    donor: "D9"
    weblink: "https://www.ncbi.nlm.nih.gov/geo/download/?acc=GSM6659419&format=file&file=GSM6659419%5FM1%5Fraw%5Ffeature%5Fbc%5Fmatrix%2Eh5"

IS_FILTERED: False
IS_ANNOTATED: False
IS_BATCHED: False

QC_RNA:
  raw_data: True

  CellbenderRemoveBackgroundRNA:
    n_splits: 10
    cuda: '' # change to '--cuda' if CUDA is installed and working
    epochs: 150
    expected-cells: 500
    checkpoint_mins: 30
    projected_ambient_count_threshold: 0.05
    empty_drop_training_fraction: 0.05

  RawFilteringRNA:
    min_genes: 200
    min_cells: 5
    n_mads: 5
    doublet_threshold: .25
    n_top_genes: 2000

  PlottingAnnotations:
    doublets: "Doublets Undefined" # All the clusters you want to remove, e.g. "Doublets Undefined T.cells"
    celltype_key: "cell_type"
    leiden_res: "leiden_res_0.50"

  MergeSamplesAnnData:
    sample_key: "sample"
    donor_key: "donor"

  TrajectoryAnalysis:
    diffusion_component: 1
    root_ctype: "Hematopoietic precursor cell"
    celltype_mask: "'Neuroblastoma cell' 'Undefined' 'Other' 'Erythroid lineage cell' 'T cell' 'NK cell'  'Myeloid cell' 'Plasmacytoid dendritic cell'" 
    n_genes: 20
    clustering_distance: 1
    cat_order: "'Hematopoietic precursor cell' 'Erythroid lineage cell' 'T cell' 'NK cell'  'Myeloid cell' 'Plasmacytoid dendritic cell' 'B cell'"
    branching: 0


### QC ATAC
QC_ATAC:
  ExportPseudobulk:
    variable: "VSN_cell_type"
    sample_id_col: "VSN_sample_id"
    n_cpu: 4
    normalize_bigwig: ""         # use "" if False, "--normalize_bigwig" if True
    split_pattern: "-"
    chromsizes: null 
# MACS2 peak calling parameters
  MACS2CallPeaks:
    format: "BEDPE"
    gsize: "hs"
    qvalue: 0.05
    shift: 73
    extsize: 146
    keep_dup: "all"
    call_summits: "--call-summits"
    nolambda: "--nolambda"
